language: python
python:
  - 3.5
  - 3.6
  - 3.7

stages:
  - test
  - name: deploy
    if: tag IS present
env:
  global:
  - TRAVIS_RUST_VERSION=nightly-2019-07-01
  - RUST_BACKTRACE=1
  - TWINE_USERNAME=pattonw

before_install:
  source ./ci/travis/setup_rust.sh

install:
  pip install -U pyo3-pack

test_template: &test_template
  stage: test
  script:
    ./ci/travis/test.sh

deploy_template: &deploy_template
  stage: deploy
  script:
    ./ci/travis/deploy.sh

jobs:
  include:
    - <<: *test_template
      python: 3.5
    - <<: *test_template
      python: 3.6
    - <<: *test_template
      dist: xenial
      python: 3.7
    - <<: *deploy_template
